[package]
name = "nim-sprague-grundy"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "debuginfo"

[dependencies]
moka = { version = "0.12.5", features = ["sync"] }
